DROP TABLE IF EXISTS Event_Participant;

DROP TABLE IF EXISTS Events;

DROP TABLE IF EXISTS Participants;

DROP TABLE IF EXISTS Specie_Location;

DROP TABLE IF EXISTS Species;

DROP TABLE IF EXISTS Categories;

DROP TABLE IF EXISTS Event_Locations;

DROP TABLE IF EXISTS Species_Locations;
